show_debug_message("Difficulty Selected: " + global.gameDifficulty)
drinks = ds_map_create() //drinks used in game
drinksMaster = ds_map_create() // master map

whiskeyRocks = ds_map_create()
ds_map_add(whiskeyRocks, "numLiquids", 1)
ds_map_add(whiskeyRocks, "whiskey", 2)
ds_map_add(whiskeyRocks, "ice", true)
ds_map_add(whiskeyRocks, "stirred", 5)
ds_map_add(whiskeyRocks, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "whiskeyRocks", whiskeyRocks)

whiskeyNeat = ds_map_create()
ds_map_add(whiskeyNeat, "numLiquids", 1)
ds_map_add(whiskeyNeat, "whiskey", 2)
ds_map_add(whiskeyNeat, "ice", false)
ds_map_add(whiskeyNeat, "stirred", 0)
ds_map_add(whiskeyNeat, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "whiskeyNeat", whiskeyNeat)

vodkaShot = ds_map_create()
ds_map_add(vodkaShot, "numLiquids", 1)
ds_map_add(vodkaShot, "vodka", 1.5)
ds_map_add(vodkaShot, "ice", false)
ds_map_add(vodkaShot, "stirred", 0)
ds_map_add(vodkaShot, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "vodkaShot", vodkaShot)

tequilaShot = ds_map_create()
ds_map_add(tequilaShot, "numLiquids", 1)
ds_map_add(tequilaShot, "tequila", 1.5)
ds_map_add(tequilaShot, "ice", false)
ds_map_add(tequilaShot, "stirred",0)
ds_map_add(tequilaShot, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "tequilaShot", tequilaShot)
	
whiteRumShot = ds_map_create()
ds_map_add(whiteRumShot, "numLiquids", 1)
ds_map_add(whiteRumShot, "whiteRum", 1.5)
ds_map_add(whiteRumShot, "ice", false)
ds_map_add(whiteRumShot, "stirred",0)
ds_map_add(whiteRumShot, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "rumShot", whiteRumShot)
	
bourbonShot = ds_map_create()
ds_map_add(bourbonShot, "numLiquids", 1)
ds_map_add(bourbonShot, "bourbon", 1.5)
ds_map_add(bourbonShot, "ice", false)
ds_map_add(bourbonShot, "stirred",0)
ds_map_add(bourbonShot, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "bourbonShot", bourbonShot)
/*
	beer1 = ds_map_create()
	ds_map_add(beer1, "numLiquids", 1)
	ds_map_add(beer1, "lightBeer", 10)
	ds_map_add(beer1, "ice", false)
	ds_map_add(beer1, "stirred",0)
	ds_map_add(beer1, "shaken", false)
	//ds_map_add(jackAndCoke, "glass", "shortTumbler")
	//ds_map_add(jackAndCoke, "garnish", ["lime"])
	ds_map_add(drinks, "beer1", beer1)

	beer2 = ds_map_create()
	ds_map_add(beer2, "numLiquids", 1)
	ds_map_add(beer2, "darkBeer", 10)
	ds_map_add(beer2, "ice", false)
	ds_map_add(beer2, "stirred",0)
	ds_map_add(beer2, "shaken", false)
	//ds_map_add(jackAndCoke, "glass", "shortTumbler")
	//ds_map_add(jackAndCoke, "garnish", ["lime"])
	ds_map_add(drinks, "beer2", beer2)
*/
whiteWine = ds_map_create()
ds_map_add(whiteWine, "numLiquids", 1)
ds_map_add(whiteWine, "whiteWine", 5)
ds_map_add(whiteWine, "ice", false)
ds_map_add(whiteWine, "stirred", 0)
ds_map_add(whiteWine, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "whiteWine", whiteWine)

redWine = ds_map_create()
ds_map_add(redWine, "numLiquids", 1)
ds_map_add(redWine, "redWine", 5)
ds_map_add(redWine, "ice", false)
ds_map_add(redWine, "stirred", 0)
ds_map_add(redWine, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
ds_map_add(drinksMaster, "redWine", redWine)

ginAndTonic = ds_map_create()
ds_map_add(ginAndTonic, "numLiquids", 2)
ds_map_add(ginAndTonic, "gin", 2)
ds_map_add(ginAndTonic, "tonic", 4)
ds_map_add(ginAndTonic, "ice", true)
ds_map_add(ginAndTonic, "stirred", 10)
ds_map_add(ginAndTonic, "shaken", false)
//ds_map_add(ginAndTonic, "glass", "shortTumbler")
ds_map_add(drinksMaster, "redWine", redWine)

vodkaRedbull = ds_map_create()
ds_map_add(vodkaRedbull, "numLiquids", 2)
ds_map_add(vodkaRedbull, "vodka", 2)
ds_map_add(vodkaRedbull, "redbull", 4)
ds_map_add(vodkaRedbull, "ice", true)
ds_map_add(vodkaRedbull, "stirred", 10)
ds_map_add(vodkaRedbull, "shaken", false)
//ds_map_add(vodkaRedbull, "glass", "shortTumbler")
ds_map_add(drinksMaster, "vodkaRedbull", vodkaRedbull)
	
jackAndCoke = ds_map_create()
ds_map_add(jackAndCoke, "numLiquids", 2)
ds_map_add(jackAndCoke, "jack", 2)
ds_map_add(jackAndCoke, "coke", 4)
ds_map_add(jackAndCoke, "ice", true)
ds_map_add(jackAndCoke, "stirred", 10)
ds_map_add(jackAndCoke, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "jackAndCoke", jackAndCoke)
	
vodkaCran = ds_map_create()
ds_map_add(vodkaCran, "numLiquids", 2)
ds_map_add(vodkaCran, "vodka", 2)
ds_map_add(vodkaCran, "cranberryJuice", 4)
ds_map_add(vodkaCran, "ice", true)
ds_map_add(vodkaCran, "stirred", 10)
ds_map_add(vodkaCran, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "vodkaCran", vodkaCran)
	
vodkaSoda = ds_map_create()
ds_map_add(vodkaSoda, "numLiquids", 2)
ds_map_add(vodkaSoda, "vodka", 2)
ds_map_add(vodkaSoda, "soda", 4)
ds_map_add(vodkaSoda, "ice", true)
ds_map_add(vodkaSoda, "stirred", 0)
ds_map_add(vodkaSoda, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinksMaster, "vodkaSoda", vodkaSoda)

if(global.gameDifficulty == "new" || global.gameDifficulty == "novice" || global.gameDifficulty == "expert")
{
	
	ds_map_add(drinks, "whiskeyRocks", whiskeyRocks)
	ds_map_add(drinks, "whiskeyNeat", whiskeyNeat)
	ds_map_add(drinks, "vodkaShot", vodkaShot)
	ds_map_add(drinks, "tequilaShot", tequilaShot)
	ds_map_add(drinks, "whiteRumShot", whiteRumShot)
	ds_map_add(drinks, "bourbonShot", bourbonShot)
	ds_map_add(drinks, "whiteWine", whiteWine)
	ds_map_add(drinks, "redWine", redWine)
	
}

if(global.gameDifficulty == "expert" || global.gameDifficulty == "novice")
{
	
	ds_map_add(drinks, "ginAndTonic", ginAndTonic)
	ds_map_add(drinks, "vodkaRedbull", vodkaRedbull)
	ds_map_add(drinks, "jackAndCoke", jackAndCoke)
	ds_map_add(drinks, "vodkaCran", vodkaCran)
	ds_map_add(drinks, "vodkaSoda", vodkaSoda)
}

if(global.gameDifficulty == "expert")
{
	/*
	mojito = ds_map_create()
	ds_map_add(mojito, "numLiquids", 4)
	ds_map_add(mojito, "whiteRum", 2)
	ds_map_add(mojito, "soda", 3)
	ds_map_add(mojito, "syrup", 1)
	ds_map_add(mojito, "limeJuice", 1)
	ds_map_add(mojito, "ice", true)
	ds_map_add(mojito, "stirred", 5)
	ds_map_add(mojito, "shaken", false)
	//ds_map_add(jackAndCoke, "glass", "shortTumbler")
	//ds_map_add(jackAndCoke, "garnish", ["lime"])
	ds_map_add(drinks, "mojito", mojito)
	*/
}