drinks = ds_map_create()

ginAndTonic = ds_map_create()
ds_map_add(ginAndTonic, "numLiquids", 2)
ds_map_add(ginAndTonic, "gin", 2)
ds_map_add(ginAndTonic, "tonic", 4)
ds_map_add(ginAndTonic, "ice", true)
ds_map_add(ginAndTonic, "stirred", true)
ds_map_add(ginAndTonic, "shaken", false)
//ds_map_add(ginAndTonic, "glass", "shortTumbler")
ds_map_add(drinks, "ginAndTonic", ginAndTonic)

vodkaRedbull = ds_map_create()
ds_map_add(vodkaRedbull, "numLiquids", 2)
ds_map_add(vodkaRedbull, "vodka", 2)
ds_map_add(vodkaRedbull, "redbull", 4)
ds_map_add(vodkaRedbull, "ice", true)
ds_map_add(vodkaRedbull, "stirred", true)
ds_map_add(vodkaRedbull, "shaken", false)
//ds_map_add(vodkaRedbull, "glass", "shortTumbler")
ds_map_add(drinks, "vodkaRedbull", vodkaRedbull)

jackAndCoke = ds_map_create()
ds_map_add(jackAndCoke, "numLiquids", 2)
ds_map_add(jackAndCoke, "jack", 2)
ds_map_add(jackAndCoke, "coke", 4)
ds_map_add(jackAndCoke, "ice", true)
ds_map_add(jackAndCoke, "stirred", true)
ds_map_add(jackAndCoke, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "jackAndCoke", jackAndCoke)

vodkaCran = ds_map_create()
ds_map_add(vodkaCran, "numLiquids", 2)
ds_map_add(vodkaCran, "vodka", 2)
ds_map_add(vodkaCran, "cran", 4)
ds_map_add(vodkaCran, "ice", true)
ds_map_add(vodkaCran, "stirred", true)
ds_map_add(vodkaCran, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "vodkaCran", vodkaCran)

vodkaSoda = ds_map_create()
ds_map_add(vodkaSoda, "numLiquids", 2)
ds_map_add(vodkaSoda, "vodka", 2)
ds_map_add(vodkaSoda, "soda", 4)
ds_map_add(vodkaSoda, "ice", true)
ds_map_add(vodkaSoda, "stirred", true)
ds_map_add(vodkaSoda, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "vodkaSoda", vodkaSoda)

whiskeyRocks = ds_map_create()
ds_map_add(whiskeyRocks, "numLiquids", 1)
ds_map_add(whiskeyRocks, "jack", 3)
ds_map_add(whiskeyRocks, "ice", true)
ds_map_add(whiskeyRocks, "stirred", false)
ds_map_add(whiskeyRocks, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "whiskeyRocks", whiskeyRocks)

whiskeyNeat = ds_map_create()
ds_map_add(whiskeyNeat, "numLiquids", 1)
ds_map_add(whiskeyNeat, "jack", 3)
ds_map_add(whiskeyNeat, "ice", false)
ds_map_add(whiskeyNeat, "stirred", false)
ds_map_add(whiskeyNeat, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "whiskeyNeat", whiskeyNeat)

vodkaShot = ds_map_create()
ds_map_add(vodkaShot, "numLiquids", 1)
ds_map_add(vodkaShot, "vodka", 2)
ds_map_add(vodkaShot, "ice", false)
ds_map_add(vodkaShot, "stirred", false)
ds_map_add(vodkaShot, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "vodkaShot", vodkaShot)

tequilaShot = ds_map_create()
ds_map_add(tequilaShot, "numLiquids", 1)
ds_map_add(tequilaShot, "tequila", 2)
ds_map_add(tequilaShot, "ice", false)
ds_map_add(tequilaShot, "stirred", false)
ds_map_add(tequilaShot, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "tequilaShot", tequilaShot)

beer1 = ds_map_create()
ds_map_add(beer1, "numLiquids", 1)
ds_map_add(beer1, "beer1", 10)
ds_map_add(beer1, "ice", false)
ds_map_add(beer1, "stirred", false)
ds_map_add(beer1, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "beer1", beer1)

beer2 = ds_map_create()
ds_map_add(beer2, "numLiquids", 1)
ds_map_add(beer2, "beer2", 10)
ds_map_add(beer2, "ice", false)
ds_map_add(beer2, "stirred", false)
ds_map_add(beer2, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "beer2", beer2)

wine1 = ds_map_create()
ds_map_add(wine1, "numLiquids", 1)
ds_map_add(wine1, "wine1", 10)
ds_map_add(wine1, "ice", false)
ds_map_add(wine1, "stirred", false)
ds_map_add(wine1, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "wine1", wine1)

wine2 = ds_map_create()
ds_map_add(wine2, "numLiquids", 1)
ds_map_add(wine2, "wine2", 10)
ds_map_add(wine2, "ice", false)
ds_map_add(wine2, "stirred", false)
ds_map_add(wine2, "shaken", false)
//ds_map_add(jackAndCoke, "glass", "shortTumbler")
//ds_map_add(jackAndCoke, "garnish", ["lime"])
ds_map_add(drinks, "wine2", wine2)